namespace ShiftFlow.Domain.Entities;

/// <summary>An admin-created assignment: inspect a set of assets (picked directly or via a Zone
/// snapshot) either individually or as a Team. Replaces the old ShiftTask+InspectionRun pairing
/// with a standalone header not tied to any shift/roster machinery.</summary>
public class InspectionOrder
{
    public int Id { get; set; }
    public string OrderNumber { get; set; } = "";      // "INS-{year}-{seq:D4}", same pattern as WorkOrder.WorkOrderNumber
    public string? Description { get; set; }

    // Exactly one of these two is set — enforced in the service layer + a DB CHECK constraint.
    public string? AssignedToUserId { get; set; } public virtual ApplicationUser? AssignedToUser { get; set; }
    public int? AssignedToTeamId { get; set; } public virtual Team? AssignedToTeam { get; set; }

    public string CreatedByUserId { get; set; } = ""; public virtual ApplicationUser CreatedByUser { get; set; } = null!;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? DueDate { get; set; }
    public DateTime? ClosedAt { get; set; }

    /// <summary>Open (nothing reported) -> InProgress (first item reported) -> PendingApproval
    /// (every item non-Pending, only when OrderType.RequiresApproval) or straight to Done (when
    /// not). Cancelled is a terminal state set by CancelAsync instead of the normal progression.</summary>
    public string Status { get; set; } = "Open";
    public static readonly string[] Statuses = ["Open", "InProgress", "PendingApproval", "Done", "Cancelled"];

    /// <summary>The admin-managed order type this order was created as — decides whether items require Action Type/Cause on Defective (OrderType.TracksDefectOutcome) and whether a defect routes to a vendor-required WorkOrder (OrderType.RequiresVendor).</summary>
    public int OrderTypeId { get; set; } public virtual OrderType? OrderType { get; set; }

    /// <summary>Set when this order was auto-generated by RecurringOrderSchedulerService rather than
    /// created manually — together with ScheduledDate, forms the dedup key (mirrors
    /// WorkOrder.SourceContractId/ScheduledDate for Preventive Maintenance).</summary>
    public int? SourceRecurringOrderId { get; set; } public virtual RecurringOrder? SourceRecurringOrder { get; set; }
    public DateTime? ScheduledDate { get; set; }

    public virtual InspectionRun? InspectionRun { get; set; }
}
